FROM debian:stable-slim
LABEL maintainer="sig-platform@spinnaker.io"

WORKDIR /opt/deck
RUN chown www-data:www-data .
COPY --chown=www-data:www-data docker /opt/deck/docker
RUN docker/setup-apache2.sh

COPY --chown=www-data:www-data build/webpack /opt/deck/html
USER www-data

CMD docker/run-apache2.sh
